mongodb:
  host: 13.211.76.5   #EC2 Instance public IP address.
  port: 27017
  username: admin
  password: password
spring:
  application:
    name: irfanstore-mongodb-service-broker
  profiles:
      active: cloud
server:
  error:
    whitelabel:
      enabled: false

security:
  basic:
    enabled: false

management:
  security:
    enabled: false
